name: Release, Publish Docker Image and Upload Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Get commit messages
        id: get_commits
        run: |
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" > commits.txt
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          cat commits.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build 
        run: go build -v -o bluesnews-rss

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Changes:
              ${{ steps.get_commits.outputs.commits }}
          draft: false
          prerelease: false
          files: |
            bluesnews-rss
            LICENSE.md
